# Generated by Django 4.0.4 on 2022-05-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='deposit_model',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=30)),
                ('Middle_Name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=100)),
                ('Deposit', models.IntegerField()),
            ],
        ),
    ]
