# Generated by Django 4.0.4 on 2022-05-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=30)),
                ('Middle_Name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=30)),
                ('Date_of_Birth', models.DateField()),
                ('Age', models.IntegerField()),
                ('Email', models.EmailField(max_length=100)),
                ('AdharCard', models.IntegerField()),
            ],
        ),
    ]
